# Generated by Django 4.2 on 2023-04-12 04:43

import backend.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=backend.core.models.upload_to),
        ),
    ]
